### ISSUE TITLE
Profile UI changes

### ISSUE THREAD

**Issue by saugatmaharjan** [Skjutsgruppen/skjutsgruppen-reactnative#229]
**TODOS**

- [ ]  New friend list UI
- [ ]  New group list UI
- [ ]  New conversation list UI
- [ ]  New trip list UI
