### ISSUE TITLE
Minor UI fixes

### ISSUE THREAD

**Issue by saugatmaharjan** [Skjutsgruppen/skjutsgruppen-reactnative#310]
**TODOS**

- [x] Increase size of map and blue ball in feed screen
- [x] Add gradient at the top of feed detail image
- [x] Increase splash screen logo size
- [x] Fixed share button in share screen
- [x] Unify modal design
- [x] Add animation in trip add progressbar
