### ISSUE TITLE
ios build issue and UI fixes 

### ISSUE THREAD

**Issue by saugatmaharjan** [Skjutsgruppen/skjutsgruppen-reactnative#359]
**TODOS**

- [x] Add custom fonts
- [x] Add drop shadow in components where required 
- [x] Remove text background
