### ISSUE TITLE
Checklist for Friday this week

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#432]
We're moving towards our release, here's a short check list for things to be done before Friday this week:

- [x] Starting with Transifex (starting today, Wednesday)

- [x] Moving everything to real Skjutsgruppen server

- [x] Connecting all old data to the app; friend connections, avatars, ride data (including comments in old rides), group data (including comments in old groups).

- [x] Facebook login and all Facebook connections should work

- [x] New onboarding is in place

- [x] Ability to share through text messages (SMS) and Facebook - this means all web versions should work as well.

**Comment by MattiasJay** [comment]
Hi team! I need you to check of the list above when you're done so I can keep track of our progress. Seems like Transifex is done now so I'm checking that of. Very well done, it looks very good! 🎉   @Skjutsgruppen/jedi

**Comment by MattiasJay** [comment]
I still only see the first check box checked. Is there any more of these checkboxes that can be checked now @manishgs @anjesh @anjhero ?

**Comment by shresthaKiran** [comment]
@MattiasJay We had been using https://www.facebook.com/(app-scoped-user-id) url to redirect to user's facebook profile page. As per this (https://developers.facebook.com/blog/post/2018/04/19/facebook-login-changes-address-abuse/), facebook no longer allows to access user's facebook profile. So, we will be removing button to redirect to users' facebook profile from the app.

/cc @anjhero

**Comment by shresthaKiran** [comment]
This issue has been resolved.
