### ISSUE TITLE
Checklist for Thursdays release

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#445]
- [x] Log in the backend that participants have agreed to participatory agreement and privacy policy / consent for us store their personal information

- [x] Participatory agreement should be on **_it's own web page_** 

- [x] ...same with privacy policy, it should be on **_it's own web page_**

- [x] Add this box that should pop up _every time_ the participant opens the app: https://projects.invisionapp.com/d/main#/console/12489615/298819021/build

- [x] In the box, Link to our Trello: http://bit.ly/skjts

- [x] In the box, Link to our Github: https://github.com/skjutsgruppen 

- [x] Change the self-sustaing garden to this: https://projects.invisionapp.com/d/main#/console/12489615/298824032/preview

- [x] App Store and Google Play should have this text: https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/407
