### ISSUE TITLE
Group related issue

### ISSUE THREAD

**Issue by shresthaKiran** [Skjutsgruppen/skjutsgruppen-reactnative#519]
- [x] Non group members should not be able to remove and add participant in open group #516
- [x] Display pink photo if no group photo in discover groups map #513 
- [x] Sms module to be opened in add participant list screen when contacts are selected in ios #511 
- [x] Cannot update group info text fix #510 
- [x] Separate modal to enter description of group #306
- [x] Separate modal to enter group name #305
- [x] Set interval for active ride to be displayed in group map #278
- [x] Display name of the group and map when group feed is scrolled #162 
- [x] Display group description in web version of card #485 
- [x] loading symbol is shown during map loading in group https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/502
- [x] standard error box is shown https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/263
- [x] Delete closed group when the last participant/enable lefts the group [167](https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/167#issuecomment-371071478)

**Comment by MattiasJay** [comment]
It's still not the actual text of the groups. Example group: https://skjutsgruppen.nu/g/23

To be clear, the rides should have the default text "We are a non-profit...."
...and groups should have the actual text.
